services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /dev/null:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/conf.d/http.conf:/etc/nginx/conf.d/http.conf:ro
      - ./nginx/conf.d/https.conf:/etc/nginx/conf.d/https.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      api:
        condition: service_healthy
    networks: [ serving ]

  api:
    build:
      context: ./be
      dockerfile: Api/Dockerfile
      args:
        INTERNAL_NUGET_HOST: ${INTERNAL_NUGET_HOST}
    container_name: api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__AppDb: "Host=postgres;Port=5432;Database=${POSTGRES_DB_APP};Username=${POSTGRES_APP_USER};Password=${POSTGRES_APP_PASS}"
      ConnectionStrings__VcsDb: "Host=postgres;Port=5432;Database=${POSTGRES_DB_VCS};Username=${POSTGRES_APP_USER};Password=${POSTGRES_APP_PASS}"
      ConnectionStrings__Redis: "redis:6379,password=${REDIS_PASS}"
      JwtSettings__Access__Secret: ${JWT_ACCESS_SECRET}
      JwtSettings__Refresh__Secret: ${JWT_REFRESH_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      flyway_app:
        condition: service_completed_successfully
      flyway_vcs:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks: [ serving, internal ]

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
      POSTGRES_APP_USER: ${POSTGRES_APP_USER}
      POSTGRES_APP_PASS: ${POSTGRES_APP_PASS}
      POSTGRES_DB_APP: ${POSTGRES_DB_APP}
      POSTGRES_DB_VCS: ${POSTGRES_DB_VCS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [ internal ]

  flyway_app:
    image: flyway/flyway:12-alpine
    container_name: flyway_app
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./be/Lib/Infrastructure/App/Migrations/Sql:/flyway/sql
    command: >
      -url=jdbc:postgresql://postgres:5432/${POSTGRES_DB_APP}
      -user=${POSTGRES_APP_USER}
      -password=${POSTGRES_APP_PASS}
      -locations=filesystem:/flyway/sql
      migrate
    networks: [ internal ]

  flyway_vcs:
    image: flyway/flyway:12-alpine
    container_name: flyway_vcs
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./be/Lib/Infrastructure/Vcs/Migrations/Sql:/flyway/sql
    command: >
      -url=jdbc:postgresql://postgres:5432/${POSTGRES_DB_VCS}
      -user=${POSTGRES_APP_USER}
      -password=${POSTGRES_APP_PASS}
      -locations=filesystem:/flyway/sql
      migrate
    networks: [ internal ]

  redis:
    image: redis:8-alpine
    container_name: redis
    restart: unless-stopped
    environment:
      REDIS_PASS: ${REDIS_PASS}
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/etc/redis/redis.conf.template:ro
      - ./redis/entrypoint.sh:/entrypoint.sh:ro
    entrypoint: [ "/bin/sh", "/entrypoint.sh" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASS}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [ internal ]

volumes:
  postgres_data:
  redis_data:

networks:
  serving:
  internal: