services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASS} 
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_APP_USER: ${POSTGRES_APP_USER}
      POSTGRES_APP_PASS: ${POSTGRES_APP_PASS}
      POSTGRES_DB_APP: ${POSTGRES_DB_APP}
      POSTGRES_DB_VCS: ${POSTGRES_DB_VCS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:8.6.2-alpine
    container_name: redis
    restart: unless-stopped
    environment:
      REDIS_PASS: ${REDIS_PASS}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/etc/redis/redis.conf.template:ro
      - ./redis/entrypoint.sh:/entrypoint.sh:ro
    entrypoint: ["/bin/sh", "/entrypoint.sh"]

volumes:
  postgres_data:
  redis_data: