// <auto-generated />
using System;
using Lib.Infrastructure.Vcs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lib.Infrastructure.Vcs.Migrations.Snapshots
{
    [DbContext(typeof(VcsDbContext))]
    [Migration("20260611105538_merge_requests")]
    partial class merge_requests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lib.Modules.Vcs.Entities.BlobMetadataEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<long>("Length")
                        .HasColumnType("bigint");

                    b.HasKey("Id", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("blob_metadata", (string)null);
                });

            modelBuilder.Entity("Lib.Modules.Vcs.Entities.CommitEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("ParentId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SecondParentId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("commits", (string)null);
                });

            modelBuilder.Entity("Lib.Modules.Vcs.Entities.MergeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MergeCommitId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceRefName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TargetRefName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("merge_requests", (string)null);
                });

            modelBuilder.Entity("Lib.Modules.Vcs.Entities.RefEntity", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CommitId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("ProjectId", "Name");

                    b.ToTable("refs", (string)null);
                });

            modelBuilder.Entity("Lib.Modules.Vcs.Entities.CommitEntity", b =>
                {
                    b.OwnsOne("Lib.Modules.Vcs.Entities.UserIdentityEntity", "Author", b1 =>
                        {
                            b1.Property<string>("CommitEntityId")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<Guid>("CommitEntityProjectId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("AuthorEmail");

                            b1.Property<Guid?>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("AuthorId");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("AuthorName");

                            b1.HasKey("CommitEntityId", "CommitEntityProjectId");

                            b1.ToTable("commits");

                            b1.WithOwner()
                                .HasForeignKey("CommitEntityId", "CommitEntityProjectId");
                        });

                    b.Navigation("Author")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
